INSERT INTO location VALUES ('54','Abhay Khand','district','1');
INSERT INTO location VALUES ('55','Abhay Khand 2','district','2');
INSERT INTO location VALUES ('56','Ahinsa Khand I','district','3');
INSERT INTO location VALUES ('57','Ahinsa Khand II','district','4');
INSERT INTO location VALUES ('58','Ambedkar Road','district','5');
INSERT INTO location VALUES ('59','Amrit Nagar','district','6');
INSERT INTO location VALUES ('60','Ankur Vihar','district','7');
INSERT INTO location VALUES ('61','Avantika','district','8');
INSERT INTO location VALUES ('62','Behta Hazipur','district','9');
INSERT INTO location VALUES ('63','Bhopura','district','10');
INSERT INTO location VALUES ('64','Bhram Puri','district','11');
INSERT INTO location VALUES ('65','Bhuapur','district','12');
INSERT INTO location VALUES ('66','Chander Nagar','district','13');
INSERT INTO location VALUES ('67','Chhapraula','district','14');
INSERT INTO location VALUES ('68','Chipiyana Buzurg','district','15');
INSERT INTO location VALUES ('69','Chiranjiv Vihar','district','16');
INSERT INTO location VALUES ('70','Crossing Republik','district','17');
INSERT INTO location VALUES ('71','Dasna','district','18');
INSERT INTO location VALUES ('72','Daulatpura','district','19');
INSERT INTO location VALUES ('73','Defence Colony','district','20');
INSERT INTO location VALUES ('74','Dhoom Manikpur','district','21');
INSERT INTO location VALUES ('75','Dilshad Extension','district','22');
INSERT INTO location VALUES ('76','Dilshad Plaza','district','23');
INSERT INTO location VALUES ('77','Dundahera','district','24');
INSERT INTO location VALUES ('78','Farukh Nagar','district','25');
INSERT INTO location VALUES ('79','Ghukna','district','26');
INSERT INTO location VALUES ('80','Govind Puram','district','27');
INSERT INTO location VALUES ('81','GT Road','district','28');
INSERT INTO location VALUES ('82','Gyan Khand I','district','29');
INSERT INTO location VALUES ('83','Gyan Khand II','district','30');
INSERT INTO location VALUES ('84','Gyan Khand III','district','31');
INSERT INTO location VALUES ('85','Gyan Khand IV','district','32');
INSERT INTO location VALUES ('86','Hapur Road','district','33');
INSERT INTO location VALUES ('87','Harbans Nagar','district','34');
INSERT INTO location VALUES ('88','Harsaon','district','35');
INSERT INTO location VALUES ('89','Hindan Residential Area','district','36');
INSERT INTO location VALUES ('90','LOCALITY','district','37');
INSERT INTO location VALUES ('91','Indirapuram','district','38');
INSERT INTO location VALUES ('92','Indraprastha Yojna','district','39');
INSERT INTO location VALUES ('93','Janakpuri','district','40');
INSERT INTO location VALUES ('94','Kala Patther','district','41');
INSERT INTO location VALUES ('95','Kamla Nehru Nagar','district','42');
INSERT INTO location VALUES ('96','Kaushambi','district','43');
INSERT INTO location VALUES ('97','Kavi Nagar','district','44');
INSERT INTO location VALUES ('98','Kinauni Village','district','45');
INSERT INTO location VALUES ('99','Koyal Enclave','district','46');
INSERT INTO location VALUES ('100','Krishna Vihar','district','47');
INSERT INTO location VALUES ('101','Lajpat Nagar','district','48');
INSERT INTO location VALUES ('102','Lal Kuan','district','49');
INSERT INTO location VALUES ('103','Lalbag Colony','district','50');
INSERT INTO location VALUES ('104','Lohia Nagar','district','51');
INSERT INTO location VALUES ('105','Loni','district','52');
INSERT INTO location VALUES ('106','Madhopura','district','53');
INSERT INTO location VALUES ('107','Madhuban Bapudham','district','54');
INSERT INTO location VALUES ('108','Mahurali','district','55');
INSERT INTO location VALUES ('109','Maliwara','district','56');
INSERT INTO location VALUES ('110','Marium Nagar','district','57');
INSERT INTO location VALUES ('111','Masuri','district','58');
INSERT INTO location VALUES ('112','Model Town','district','59');
INSERT INTO location VALUES ('113','Modinagar','district','60');
INSERT INTO location VALUES ('114','Mohan Nagar','district','61');
INSERT INTO location VALUES ('115','Muradnagar','district','62');
INSERT INTO location VALUES ('116','Nai Basti Dundahera','district','63');
INSERT INTO location VALUES ('117','Nandgram','district','64');
INSERT INTO location VALUES ('118','Naya Ganj','district','65');
INSERT INTO location VALUES ('119','Neelmani Colony','district','66');
INSERT INTO location VALUES ('120','Nehru Nagar','district','67');
INSERT INTO location VALUES ('121','Nehru Nagar-II','district','68');
INSERT INTO location VALUES ('122','Nehru Nagar-III','district','69');
INSERT INTO location VALUES ('123','NH-24','district','70');
INSERT INTO location VALUES ('124','NH-58','district','71');
INSERT INTO location VALUES ('125','NH-91','district','72');
INSERT INTO location VALUES ('126','Niti Khand I','district','73');
INSERT INTO location VALUES ('127','LOCALITY','district','74');
INSERT INTO location VALUES ('128','Niti Khand II','district','75');
INSERT INTO location VALUES ('129','Niti Khand III','district','76');
INSERT INTO location VALUES ('130','Nyay Khand I','district','77');
INSERT INTO location VALUES ('131','Nyay Khand II','district','78');
INSERT INTO location VALUES ('132','Nyay Khand III','district','79');
INSERT INTO location VALUES ('133','Panchsheel Enclave','district','80');
INSERT INTO location VALUES ('134','Pandav Nagar','district','81');
INSERT INTO location VALUES ('135','Patel Nagar','district','82');
INSERT INTO location VALUES ('136','Pilkhuwa','district','83');
INSERT INTO location VALUES ('137','Pratap Vihar','district','84');
INSERT INTO location VALUES ('138','Raghunathpur','district','85');
INSERT INTO location VALUES ('139','Raispur','district','86');
INSERT INTO location VALUES ('140','Raj Nagar','district','87');
INSERT INTO location VALUES ('141','Raj Nagar Extension','district','88');
INSERT INTO location VALUES ('142','Rajendra Nagar','district','89');
INSERT INTO location VALUES ('143','Ramprastha','district','90');
INSERT INTO location VALUES ('144','RK Puram','district','91');
INSERT INTO location VALUES ('145','Sadiqpur','district','92');
INSERT INTO location VALUES ('146','Sahibabad','district','93');
INSERT INTO location VALUES ('147','Sanjay Nagar','district','94');
INSERT INTO location VALUES ('148','Sehani Khurd','district','95');
INSERT INTO location VALUES ('149','Sewa Nagar','district','96');
INSERT INTO location VALUES ('150','Shahpur Bamheta','district','97');
INSERT INTO location VALUES ('151','Shakti Khand I','district','98');
INSERT INTO location VALUES ('152','Shakti Khand II','district','99');
INSERT INTO location VALUES ('153','Shakti Khand III','district','100');
INSERT INTO location VALUES ('154','Shakti Khand IV','district','101');
INSERT INTO location VALUES ('155','Shalimar Garden','district','102');
INSERT INTO location VALUES ('156','Shalimar Garden Extention 1','district','103');
INSERT INTO location VALUES ('157','Shalimar Garden Extention 2','district','104');
INSERT INTO location VALUES ('158','Shastri Nagar','district','105');
INSERT INTO location VALUES ('159','Shatabdipuram','district','106');
INSERT INTO location VALUES ('160','Siddharth Vihar','district','107');
INSERT INTO location VALUES ('161','Surya Nagar','district','108');
INSERT INTO location VALUES ('162','Swaran Jyanti Puram','district','109');
INSERT INTO location VALUES ('163','Trans Delhi Signature City','district','110');
INSERT INTO location VALUES ('164','LOCALITY','district','111');
INSERT INTO location VALUES ('165','Vaibhav Khand','district','112');
INSERT INTO location VALUES ('166','Vaishali','district','113');
INSERT INTO location VALUES ('167','Vaishali Extension','district','114');
INSERT INTO location VALUES ('168','Vaishali Sector-1','district','115');
INSERT INTO location VALUES ('169','Vaishali Sector-2','district','116');
INSERT INTO location VALUES ('170','Vaishali Sector-3','district','117');
INSERT INTO location VALUES ('171','Vaishali Sector-5','district','118');
INSERT INTO location VALUES ('172','Vaishali Sector-9','district','119');
INSERT INTO location VALUES ('173','Vasundhara','district','120');
INSERT INTO location VALUES ('174','Vasundhara Sector-1','district','121');
INSERT INTO location VALUES ('175','Vasundhara Sector-10','district','122');
INSERT INTO location VALUES ('176','Vasundhara Sector-11','district','123');
INSERT INTO location VALUES ('177','Vasundhara Sector-12','district','124');
INSERT INTO location VALUES ('178','Vasundhara Sector-13','district','125');
INSERT INTO location VALUES ('179','Vasundhara Sector-14','district','126');
INSERT INTO location VALUES ('180','Vasundhara Sector-15','district','127');
INSERT INTO location VALUES ('181','Vasundhara Sector-16','district','128');
INSERT INTO location VALUES ('182','Vasundhara Sector-17','district','129');
INSERT INTO location VALUES ('183','Vasundhara Sector-18','district','130');
INSERT INTO location VALUES ('184','Vasundhara Sector-19','district','131');
INSERT INTO location VALUES ('185','Vasundhara Sector-2A','district','132');
INSERT INTO location VALUES ('186','Vasundhara Sector-2B','district','133');
INSERT INTO location VALUES ('187','Vasundhara Sector-2C','district','134');
INSERT INTO location VALUES ('188','Vasundhara Sector-3','district','135');
INSERT INTO location VALUES ('189','Vasundhara Sector-4','district','136');
INSERT INTO location VALUES ('190','Vasundhara Sector-5','district','137');
INSERT INTO location VALUES ('191','Vasundhara Sector-6','district','138');
INSERT INTO location VALUES ('192','Vasundhara Sector-7','district','139');
INSERT INTO location VALUES ('193','Vasundhara Sector-8','district','140');
INSERT INTO location VALUES ('194','Vasundhara Sector-9','district','141');
INSERT INTO location VALUES ('195','Ved Vihar','district','142');
INSERT INTO location VALUES ('196','Vijay Nagar','district','143');
INSERT INTO location VALUES ('197','Vikram Enclave','district','144');
INSERT INTO location VALUES ('198','Wave City','district','145');
